exports.reactors = [
  {
    "name": "",
    "grossPower": "This article needs to be updated. Please help update this article to reflect recent events or newly available information.  (June 2021)",
    "type": "",
    "producer": "",
    "country": "",
    "status": ""
  },
  {
    "name": "",
    "grossPower": "",
    "type": "",
    "producer": "",
    "country": "",
    "status": ""
  },
  {
    "name": "4S",
    "nameLink": "/wiki/Toshiba_4S",
    "grossPower": "10–50",
    "type": "SFR",
    "typeLink": "/wiki/Sodium-cooled_fast_reactor",
    "producer": "Toshiba",
    "producerLink": "/wiki/Toshiba",
    "country": "Japan",
    "status": "Detailed design"
  },
  {
    "name": "ABV-6",
    "nameLink": "/w/index.php?title=ABV_Reactor&action=edit&redlink=1",
    "grossPower": "6–9",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "OKBM Afrikantov",
    "producerLink": "/wiki/OKBM_Afrikantov",
    "country": "Russia",
    "status": "Detailed design"
  },
  {
    "name": "ACP100 Linglong One",
    "nameLink": "/wiki/ACP100",
    "grossPower": "125",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "China National Nuclear Corporation",
    "producerLink": "/wiki/China_National_Nuclear_Corporation",
    "country": "China",
    "status": "Under Construction [2]"
  },
  {
    "name": "TMSR-LF1",
    "nameLink": "/wiki/TMSR-LF1",
    "grossPower": "10[3]",
    "type": "MSR",
    "typeLink": "/wiki/Molten_salt_reactor",
    "producer": "China National Nuclear Corporation",
    "producerLink": "/wiki/China_National_Nuclear_Corporation",
    "country": "China",
    "status": "Under Construction"
  },
  {
    "name": "ARC-100",
    "nameLink": "/w/index.php?title=ARC-100&action=edit&redlink=1",
    "grossPower": "100",
    "type": "SFR",
    "typeLink": "/wiki/Sodium-cooled_fast_reactor",
    "producer": "ARC Nuclear",
    "producerLink": "/w/index.php?title=ARC_Nuclear&action=edit&redlink=1",
    "country": "Canada",
    "status": "Design: Vendor design review.[4] One unit approved for construction at Point Lepreau Nuclear Generating Station in December 2019.[5]"
  },
  {
    "name": "MMR",
    "nameLink": "/w/index.php?title=Micro_Modular_Reactor&action=edit&redlink=1",
    "grossPower": "5",
    "type": "HTGR",
    "typeLink": "/wiki/High_temperature_gas_cooled_reactor",
    "producer": "Ultra Safe Nuclear Corporation",
    "producerLink": "/w/index.php?title=Ultra_Safe_Nuclear_Corporation&action=edit&redlink=1",
    "country": "U.S.A / Canada",
    "status": "Licensing stage [6]"
  },
  {
    "name": "ANGSTREM[7]",
    "nameLink": "/w/index.php?title=ANGSTREM&action=edit&redlink=1",
    "grossPower": "6",
    "type": "LFR",
    "typeLink": "/wiki/Lead-cooled_fast_reactor",
    "producer": "OKB Gidropress",
    "producerLink": "/wiki/OKB_Gidropress",
    "country": "Russia",
    "status": "Conceptual design"
  },
  {
    "name": "B&W mPower",
    "nameLink": "/wiki/B%26W_mPower",
    "grossPower": "195",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "Babcock & Wilcox",
    "producerLink": "/wiki/Babcock_%26_Wilcox",
    "country": "United States",
    "status": "Cancelled in March 2017"
  },
  {
    "name": "BANDI-60",
    "grossPower": "60",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "KEPCO",
    "producerLink": "/wiki/Korea_Electric_Power_Corporation",
    "country": "South Korea",
    "status": "Detailed design[8]"
  },
  {
    "name": "BREST-OD-300[9]",
    "nameLink": "/wiki/BREST_(Reactor)",
    "grossPower": "300",
    "type": "LFR",
    "typeLink": "/wiki/Lead-cooled_fast_reactor",
    "producer": "Atomenergoprom",
    "producerLink": "/wiki/Atomenergoprom",
    "country": "Russia",
    "status": "Under construction[10]"
  },
  {
    "name": "BWRX-300[11]",
    "nameLink": "/wiki/BWRX-300",
    "grossPower": "300",
    "type": "ABWR",
    "typeLink": "/wiki/Advanced_Boiling_Water_Reactor",
    "producer": "GE Hitachi Nuclear Energy",
    "producerLink": "/wiki/GE_Hitachi_Nuclear_Energy",
    "country": "United States",
    "status": "Licensing stage"
  },
  {
    "name": "CAREM",
    "nameLink": "/wiki/CAREM",
    "grossPower": "27–30",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "CNEA",
    "producerLink": "/wiki/CNEA",
    "country": "Argentina",
    "status": "Under construction"
  },
  {
    "name": "Copenhagen Atomics Waste Burner",
    "grossPower": "50",
    "type": "MSR",
    "typeLink": "/wiki/Molten_salt_reactor",
    "producer": "Copenhagen Atomics",
    "producerLink": "/wiki/Copenhagen_Atomics",
    "country": "Denmark",
    "status": "Conceptual design"
  },
  {
    "name": "HTR-PM",
    "nameLink": "/wiki/HTR-PM",
    "grossPower": "210 (2 reactors one turbine)",
    "type": "HTGR",
    "producer": "China Huaneng",
    "producerLink": "/wiki/China_Huaneng_Group",
    "country": "China",
    "status": "One reactor connected to grid in December 2021.[12]"
  },
  {
    "name": "ELENA[13][14]",
    "nameLink": "/wiki/ELENA_reactor",
    "grossPower": "0.068",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "Kurchatov Institute",
    "producerLink": "/wiki/Kurchatov_Institute",
    "country": "Russia",
    "status": "Conceptual design"
  },
  {
    "name": "Energy Well[15]",
    "nameLink": "/w/index.php?title=Energy_Well&action=edit&redlink=1",
    "grossPower": "8.4",
    "type": "MSR",
    "typeLink": "/wiki/Molten_salt_reactor",
    "producer": "cs:Centrum výzkumu Řež[16]",
    "producerLink": "https://cs.wikipedia.org/wiki/Centrum_v%C3%BDzkumu_%C5%98e%C5%BE",
    "country": "Czechia",
    "status": "Conceptual design"
  },
  {
    "name": "Flexblue",
    "nameLink": "/wiki/Flexblue",
    "grossPower": "160",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "Areva TA / DCNS group",
    "producerLink": "/wiki/Areva",
    "country": "France",
    "status": "Conceptual design"
  },
  {
    "name": "Fuji MSR",
    "nameLink": "/wiki/Fuji_MSR",
    "grossPower": "200",
    "type": "MSR",
    "typeLink": "/wiki/Molten_salt_reactor",
    "producer": "International Thorium Molten Salt Forum (ITMSF)",
    "country": "Japan",
    "status": "Conceptual design"
  },
  {
    "name": "GT-MHR",
    "nameLink": "/wiki/GT-MHR",
    "grossPower": "285",
    "type": "GTMHR",
    "typeLink": "/wiki/Gas_turbine_modular_helium_reactor",
    "producer": "OKBM Afrikantov",
    "producerLink": "/wiki/OKBM_Afrikantov",
    "country": "Russia",
    "status": "Conceptual design completed"
  },
  {
    "name": "G4M",
    "nameLink": "/wiki/Gen4_Energy",
    "grossPower": "25",
    "type": "LFR",
    "typeLink": "/wiki/Lead-cooled_fast_reactor",
    "producer": "Gen4 Energy",
    "producerLink": "/wiki/Gen4_Energy",
    "country": "United States",
    "status": "Conceptual design"
  },
  {
    "name": "GT-MHR",
    "nameLink": "/wiki/GT-MHR",
    "grossPower": "50",
    "type": "GTMHR",
    "typeLink": "/wiki/Gas_turbine_modular_helium_reactor",
    "producer": "General Atomics, Framatom",
    "producerLink": "/wiki/General_Atomics",
    "country": "United States,France",
    "status": "Conceptual design"
  },
  {
    "name": "IMSR400",
    "nameLink": "/wiki/IMSR",
    "grossPower": "185–192",
    "type": "MSR",
    "typeLink": "/wiki/Molten_salt_reactor",
    "producer": "Terrestrial Energy[17]",
    "producerLink": "/wiki/Terrestrial_Energy",
    "country": "Canada",
    "status": "Conceptual design"
  },
  {
    "name": "TMSR-500",
    "nameLink": "/wiki/TMSR-500",
    "grossPower": "500",
    "type": "MSR",
    "typeLink": "/wiki/Molten_salt_reactor",
    "producer": "ThorCon[18]",
    "producerLink": "/w/index.php?title=ThorCon&action=edit&redlink=1",
    "country": "Indonesia",
    "status": "Conceptual design"
  },
  {
    "name": "IRIS",
    "nameLink": "/wiki/International_Reactor_Innovative_and_Secure",
    "grossPower": "335",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "Westinghouse-led",
    "producerLink": "/wiki/Westinghouse_Electric_Company",
    "country": "international",
    "status": "Design (Basic)"
  },
  {
    "name": "KLT-40S Akademik Lomonosov",
    "nameLink": "/wiki/KLT-40",
    "grossPower": "70",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "OKBM Afrikantov",
    "producerLink": "/wiki/OKBM_Afrikantov",
    "country": "Russia",
    "status": "Operating, May 2020[19] (floating plant)"
  },
  {
    "name": "MCSFR",
    "nameLink": "/w/index.php?title=MCSFR&action=edit&redlink=1",
    "grossPower": "50–1000",
    "type": "MCSFR",
    "typeLink": "/w/index.php?title=Molten_Chloride_Salt_Fast_Reactor&action=edit&redlink=1",
    "producer": "Elysium Industries",
    "producerLink": "/wiki/Elysium_Industries",
    "country": "United States",
    "status": "Conceptual design"
  },
  {
    "name": "MHR-100",
    "nameLink": "/w/index.php?title=MHR-100&action=edit&redlink=1",
    "grossPower": "25–87",
    "type": "HTGR",
    "typeLink": "/wiki/High_temperature_gas_cooled_reactor",
    "producer": "OKBM Afrikantov",
    "producerLink": "/wiki/OKBM_Afrikantov",
    "country": "Russia",
    "status": "Conceptual design"
  },
  {
    "name": "MHR-T[a]",
    "nameLink": "/w/index.php?title=MHR-T&action=edit&redlink=1",
    "grossPower": "205.5 (x4)",
    "type": "HTGR",
    "typeLink": "/wiki/High_temperature_gas_cooled_reactor",
    "producer": "OKBM Afrikantov",
    "producerLink": "/wiki/OKBM_Afrikantov",
    "country": "Russia",
    "status": "Conceptual design"
  },
  {
    "name": "MRX",
    "grossPower": "30–100",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "JAERI",
    "producerLink": "/wiki/JAERI",
    "country": "Japan",
    "status": "Conceptual design"
  },
  {
    "name": "NP-300",
    "nameLink": "/w/index.php?title=NP-300&action=edit&redlink=1",
    "grossPower": "100–300",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "Areva TA",
    "producerLink": "/wiki/Areva",
    "country": "France",
    "status": "Conceptual design"
  },
  {
    "name": "NuScale",
    "nameLink": "/wiki/NuScale",
    "grossPower": "45",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "NuScale Power LLC",
    "producerLink": "/wiki/NuScale_Power",
    "country": "United States",
    "status": "Licensing stage"
  },
  {
    "name": "Nuward",
    "nameLink": "/w/index.php?title=Nuward&action=edit&redlink=1",
    "grossPower": "300–400",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "consortium",
    "country": "France",
    "status": "Conceptual design, construction anticipated in 2030[20]"
  },
  {
    "name": "OPEN100",
    "nameLink": "/wiki/OPEN100",
    "grossPower": "100",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "Energy Impact Center",
    "producerLink": "/wiki/Energy_Impact_Center",
    "country": "United States",
    "status": "Conceptual design[21]"
  },
  {
    "name": "PBMR-400",
    "nameLink": "/wiki/PBMR",
    "grossPower": "165",
    "type": "HTGR",
    "typeLink": "/wiki/High_temperature_gas_cooled_reactor",
    "producer": "Eskom",
    "producerLink": "/wiki/Eskom",
    "country": "South Africa",
    "status": "Cancelled. Postponed indefinitely[22]"
  },
  {
    "name": "Rolls-Royce SMR",
    "nameLink": "/wiki/Rolls-Royce_SMR",
    "grossPower": "470",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "Rolls-Royce",
    "producerLink": "/wiki/Rolls-Royce_Holdings",
    "country": "United Kingdom",
    "status": "Design stage"
  },
  {
    "name": "SEALER[23][24]",
    "nameLink": "/w/index.php?title=SEALER&action=edit&redlink=1",
    "grossPower": "55",
    "type": "LFR",
    "typeLink": "/wiki/Lead-cooled_fast_reactor",
    "producer": "LeadCold",
    "country": "Sweden",
    "status": "Design stage"
  },
  {
    "name": "SMART",
    "nameLink": "/w/index.php?title=System-integrated_Modular_Advanced_ReacTor&action=edit&redlink=1",
    "grossPower": "100",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "KAERI",
    "producerLink": "/wiki/KAERI",
    "country": "South Korea",
    "status": "Licensed"
  },
  {
    "name": "SMR-160",
    "nameLink": "/wiki/SMR-160",
    "grossPower": "160",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "Holtec International",
    "producerLink": "/wiki/Holtec_International",
    "country": "United States",
    "status": "Conceptual design"
  },
  {
    "name": "SVBR-100[25][26]",
    "nameLink": "/w/index.php?title=SVBR&action=edit&redlink=1",
    "grossPower": "100",
    "type": "LFR",
    "typeLink": "/wiki/Lead-cooled_fast_reactor",
    "producer": "OKB Gidropress",
    "producerLink": "/wiki/OKB_Gidropress",
    "country": "Russia",
    "status": "Detailed design"
  },
  {
    "name": "SSR-W",
    "nameLink": "/wiki/Stable_Salt_Reactor",
    "grossPower": "300–1000",
    "type": "MSR",
    "typeLink": "/wiki/Molten_salt_reactor",
    "producer": "Moltex Energy[27]",
    "producerLink": "#cite_note-28",
    "country": "United Kingdom",
    "status": "Conceptual design"
  },
  {
    "name": "S-PRISM",
    "nameLink": "/wiki/S-PRISM",
    "grossPower": "311",
    "type": "FBR",
    "typeLink": "/wiki/Breeder_reactor#Fast_breeder_reactor",
    "producer": "GE Hitachi Nuclear Energy",
    "producerLink": "/wiki/GE_Hitachi_Nuclear_Energy",
    "country": "United States/Japan",
    "status": "Detailed design"
  },
  {
    "name": "U-Battery",
    "nameLink": "/wiki/U-Battery",
    "grossPower": "4",
    "type": "HTGR",
    "typeLink": "/wiki/High_temperature_gas_cooled_reactor",
    "producer": "U-Battery consortium[b]",
    "producerLink": "#cite_note-29",
    "country": "United Kingdom",
    "status": "Design and development work[28][29]"
  },
  {
    "name": "VBER-300",
    "nameLink": "/wiki/VBER-300",
    "grossPower": "325",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "OKBM Afrikantov",
    "producerLink": "/wiki/OKBM_Afrikantov",
    "country": "Russia",
    "status": "Licensing stage"
  },
  {
    "name": "VK-300",
    "nameLink": "/w/index.php?title=VK-300&action=edit&redlink=1",
    "grossPower": "250",
    "type": "BWR",
    "typeLink": "/wiki/BWR",
    "producer": "Atomstroyexport",
    "producerLink": "/wiki/Atomstroyexport",
    "country": "Russia",
    "status": "Detailed design"
  },
  {
    "name": "VVER-300",
    "nameLink": "/w/index.php?title=VVER-300&action=edit&redlink=1",
    "grossPower": "300",
    "type": "BWR",
    "typeLink": "/wiki/BWR",
    "producer": "OKB Gidropress",
    "producerLink": "/wiki/OKB_Gidropress",
    "country": "Russia",
    "status": "Conceptual design"
  },
  {
    "name": "Westinghouse SMR",
    "grossPower": "225",
    "type": "PWR",
    "typeLink": "/wiki/Pressurized_water_reactor",
    "producer": "Westinghouse Electric Company",
    "producerLink": "/wiki/Westinghouse_Electric_Company",
    "country": "United States",
    "status": "Cancelled. Preliminary design completed.[30]"
  },
  {
    "name": "Xe-100",
    "nameLink": "/w/index.php?title=Xe-100&action=edit&redlink=1",
    "grossPower": "80",
    "type": "HTGR",
    "typeLink": "/wiki/High_temperature_gas_cooled_reactor",
    "producer": "X-energy[31]",
    "producerLink": "/wiki/X-energy",
    "country": "United States",
    "status": "Conceptual design development"
  },
  {
    "name": "Updated as of 2014. Some reactors are not included in IAEA Report.[1] Not all IAEA reactors are listed there are added yet and some are added (anno 2021) that were not yet listed in the now dated IAEA report.",
    "nameLink": "#cite_note-iaea-2014-1",
    "grossPower": "",
    "type": "",
    "producer": "",
    "country": "",
    "status": ""
  }
]